# LightGBM model hyperparameters
model_params:
    # Core
    task: train
    objective: regression
    boosting: gbdt
    learning_rate: 0.01
    num_leaves: 59
    num_threads: -1
    device: gpu
    # Learning control
    max_depth: 10
    min_data_in_leaf: 17
    min_sum_hessian_in_leaf: 0.005742040618301125
    bagging_fraction: 0.5528902981527475
    bagging_freq: 1
    feature_fraction: 0.691847185757147
    lambda_l1: 0.1312275046470146
    lambda_l2: 0.1293457364590906
    cat_smooth: 76
    verbose: 1
    # Metric
#     metric:

    # Standard API fit_params
    n_estimators: 10000    # 2500
    verbose_eval: 250
    early_stopping_round: 500
#     es_rounds: 500   # Early stopping rounds

    random_state: 42

fit_params:
    eval_metric: rmse
