# Configuration for data processor
# =Features=
feats: [
    # =TID=
    'Date',
    # =Location=
    'Lat', 'Lon', 'Loc',
    # =Generator=
    'Module',
    'Capacity',
    'Irradiance_m', 'Temp_m',
    'Angle',
    # =Press=
    'StnPres', 'StnPresMax', 'StnPresMin', 'SeaPres',
    'StnPres_i', 'StnPresMax_i', 'StnPresMin_i',
    # =Irradiance=
    'Irradiance', 'SunShine', 'SunLightHr', 'SunRise',
    'SunSet', 'ZenithAngle', 'AirMassNoon',
    'Irradiance_i',
    # =Temperature=
    'Temp', 'TempMax', 'TempMin', 'TdDewPoint',
    'Temp_t', 'Temp_i', 'TempMax_i', 'TempMin_i',
    # =Humidity=
    'RH', 'RHMin',
    'RH_i', 'RHMin_i',
    # =Wind=
    'WS', 'WSGust', 'WD', 'WDGust',
    'WS_i', 'WD_i', 'WSGust_i', 'WDGust_i',
    # =Precipitation (All with 75%~80% up zero values in train/test.)=
    'Precp', 'PrecpMax10', 'PrecpMax60',
    'Precp_i',
    # =AQ=
    'COMean', 'COMin', 'COMax', 'COMedian', 'COStd', 'COSkew', 'COKurt',
    'NO2Mean', 'NO2Min', 'NO2Max', 'NO2Median', 'NO2Std', 'NO2Skew', 'NO2Kurt',
    'O3Mean', 'O3Min', 'O3Max', 'O3Median', 'O3Std', 'O3Skew', 'O3Kurt',
    'PM10Mean', 'PM10Min', 'PM10Max', 'PM10Median', 'PM10Std', 'PM10Skew', 'PM10Kurt',
    'PM2.5Mean', 'PM2.5Min', 'PM2.5Max', 'PM2.5Median', 'PM2.5Std', 'PM2.5Skew', 'PM2.5Kurt',
    'SO2Mean', 'SO2Min', 'SO2Max', 'SO2Median', 'SO2Std', 'SO2Skew', 'SO2Kurt',
    # =Target Encoding=
    'GenMean', 'GenMonthMean',
]

# =Feature engineering=
fe:
    add_month: False
    add_module_meta: False
    label_enc: []
    mine_temp: []
    mine_irrad: []
    meta_feats: []
    knn_meta_feats: {}

# =Drop outliers=
drop_outliers: top3

# =Holdout=
holdout:
    n_splits: 0
    chrono: null #False
    ts_col: null #Date
    t_start: null #["2021-08-28", "2021-09-28"]
    t_end: null #["2021-09-28", "2021-10-28"]
    holdout_ratio: null  # 0.2

# =Scaling=
scale:
    type: null
    n_quantiles: null
    cols: []

# =DL Dataset=
dataset: null
    # t_window: 28
    # horizon: 0   # Use features on the same day
    # use_capacity: False
